INSERT INTO Especies (nomecientifico,nomecomum)
VALUES
    ('Acer pseudoplatanus', 'Bordo'),
    ('Acer pseudoplatanus Erectum', 'Bordo Vermelho'),
    ('Acer rubrum Columnare', 'Bordo Vermelho'),
    ('Acer rubrum Scanlon', 'Bordo Vermelho'),
    ('Aesculus hippocastanum', 'Castanheiro-da-índia'),
    ('Aesculus x carnea', 'Castanheiro-vermelho-da-índia'),
    ('Albizia julibrissin', 'Albizia'),
    ('Albizia julibrissin', 'Mimosa'),
    ('Betula alba', 'Vidoeiro-branco'),
    ('Betula albosinensis', 'Vidoeiro vermelho chinês'),
    ('Betula celtiberica', 'Vidoeiro-Português'),
    ('Betula nigra', 'Vidoeiro-preto'),
    ('Betula nigra', 'Vidoeiro-ribeirinho'),
    ('Betula pubescens', 'Vidoeiro comum'),
    ('Betula sp.', 'Vidoeiro comum'),
    ('Betula utilis var. Jacquemontii', 'Vidoeiro Branco Dos Himalaias'),
    ('Betula verrocosa Fastigiata (= B.pendula)', 'Vidoeiro-branco'),
    ('Carpinus betulus', 'Carpa europeia'),
    ('Carpinus betulus Fastigiata', 'Carpa europeia'),
    ('Casuarina equisetifolia', 'Árvore da tristeza'),
    ('Casuarina equisetifolia', 'Pinheiro-da-Austrália'),
    ('Catalpa bignonioides', 'Árvore-das-trombetas'),
    ('Cercis siliquastrum', 'Árvore de judas'),
    ('Cercis siliquastrum', 'Olaia'),
    ('Chorisia speciosa', 'Ceiba espinhosa'),
    ('Chorisia speciosa', 'Paineira'),
    ('Corylus colurna', 'Aveleira turca'),
    ('Crataegus laevigata', 'Espinheiro-branco'),
    ('Crataegus laevigata', 'Pilriteiro'),
    ('Crataegus laevigata Paul s Scarlet', 'Pilriteiro'),
    ('Crataegus monogyna Stricta', 'Espinheiro-branco'),
    ('Crataegus monogyna Stricta', 'Pilriteiro'),
    ('Crataegus sp.', 'Espinheiro'),
    ('Fagus sylvatica', 'Faia'),
    ('Fagus sylvatica Dawyck', 'Faia'),
    ('Fraxinus excelsior ', 'Freixo'),
    ('Ginkgo biloba ', 'Nogueira-do-japão'),
    ('Liquidambar styraciflua', 'Árvore-do-âmbar'),
    ('Liquidambar styraciflua', 'Liquidambar'),
    ('Liquidambar styraciflua Stricta', 'Árvore-do-âmbar'),
    ('Liquidambar styraciflua Stricta', 'Liquidambar'),
    ('Liriodendron tulipifera', 'Tulipeiro'),
    ('Liriodendron tulipifera Fastigiata', 'Tulipeiro'),
    ('Magnolia sp.', 'Magnólia'),
    ('Magnolia stellata', 'Magnólia-estrela'),
    ('Magnolia x soulangeana', 'Magnólia-chinesa'),
    ('Malus sp.', 'Macieira- selvagem'),
    ('Malus trilobata', 'Macieira- selvagem'),
    ('Malus tschonoskii', 'Macieira- selvagem'),
    ('Malus Van Eseltine', 'Macieira- selvagem'),
    ('Melia azederach', 'Amargoseira'),
    ('Melia azederach', 'Mélia'),
    ('Nothofagus betuloides', 'Faia de magalhães'),
    ('Nothofagus sp.', 'Faia falsa '),
    ('Olea europea', 'Oliveira'),
    ('Phoenix canarensis', 'Palmeira-Das-Canárias'),
    ('Platanus orientalis', 'Plátano'),
    ('Populus nigra ', 'Choupo negro'),
    ('Prunus avium Plena', 'Cerejeira selvagem'),
    ('Prunus cerasifera Pissardii', 'Ameixoeira-dos-jardins'),
    ('Prunus serrulata Amanogawa', 'Cerejeira-ornamental'),
    ('Prunus Spire ( Hibrido)', 'Cerejeira - vermelha'),
    ('Quercus coccinea', 'Carvalho-americano- vermelho'),
    ('Quercus robur', 'Carvalho-alvarinho'),
    ('Quercus robur Fastigiata', 'Carvalho-alvarinho'),
    ('Quercus rubra', 'Carvalho-americano'),
    ('Quercus sp.', 'Carvalho'),
    ('Sorbus aucuparia', 'Sorveira-brava'),
    ('Sorbus aucuparia Beissneri', 'Sorveira-brava'),
    ('Sorbus aucuparia Fastigiata', 'Sorveira-brava'),
    ('Sorbus sp.', 'Sorveira'),
    ('Sorbus x thuringia Fastigiata ( Hibrido)', 'Sorveira-brava'),
    ('Tilia cordata', 'Tilia de folha pequena'),
    ('Tilia platyphyllos', 'Tilia de folha grande');